# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentId',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='idNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
