# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(default='', max_length=300),
        ),
    ]
