# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0002_auto_20180226_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentId',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='idNumber',
        ),
    ]
