# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0004_auto_20180228_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/images/user_image.png', upload_to='profile_images'),
        ),
    ]
