# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0005_auto_20180308_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
