# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='isStudent',
            field=models.BooleanField(),
        ),
    ]
