# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0007_auto_20180309_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/user_image.png', upload_to='profile_images'),
        ),
    ]
