# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0013_auto_20180312_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isStudent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='Student', max_length=7),
        ),
    ]
