# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0014_auto_20180312_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachedFile',
            field=models.FileField(default='', upload_to='lab_files'),
        ),
    ]
