# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0015_post_attachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachedFile',
            field=models.FileField(blank=True, default='', null=True, upload_to='lab_files/'),
        ),
    ]
