# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0016_auto_20180315_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedIn',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(default='', max_length=300),
        ),
    ]
