# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0017_auto_20180316_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedIn',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(default='', max_length=300),
        ),
    ]
