# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLabShare', '0018_auto_20180316_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachedFile',
            field=models.FileField(blank=True, default='', null=True, upload_to='lab_files'),
        ),
    ]
